### ISSUE TITLE
Wat is dit?

### ISSUE THREAD

**Issue by KrijnHoetmer** [Ronabundy1/the-client-website#7]
Kun je uitleggen wat deze regel precies doet of betekent? Vergeet niet HTML semantiek toe te passen in je project.

https://github.com/Ronabundy1/the-client-website/blob/2b25c4aa5031a30604e16f0ce1e742a979f43b76/index.html#L203

**Comment by Ronabundy1** [comment]
Dit is niet van relevante toepassing omdat ik niet meer met bootstrap werk.
